# Generated by Django 2.2.1 on 2019-05-17 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=200)),
                ('apellido1_persona', models.CharField(max_length=200)),
                ('apellido2_persona', models.CharField(max_length=200)),
                ('edad_persona', models.IntegerField()),
                ('telefono_persona', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=200)),
                ('edad_mascota', models.IntegerField()),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Persona')),
            ],
        ),
    ]
