# Generated by Django 2.2.1 on 2019-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido1_persona']},
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
